replicaCount: 2

image:
  repository: vishwacloudlab/jenkins-docker-lab
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000
  targetPort: 5000
  nodePort: 30080

resources: {}
